#variables from files
- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hello we are learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}}."